### ISSUE TITLE
Feature Request - Support Unix Shebang (#!) for executable scritps.

### ISSUE THREAD

**Issue by ejasiunas** [kenmartin-unix/BwBasic#1]
Request bwbasic ignore lines beginning with #!.
Inserting the following code into the bwb_fload function (see below) works.

   else if (bwb_strnicmp (tbuf, "#!", 2) == 0)
    {
      /* Shebang - executable script Linux */
      /* Ignore Line - ejj added 18apr23*/
    }

This would allow bwbasic to be used for executable scripts.

----------------------------------------
bwb_fload function     ---------------
----------------------------------------
extern int
bwb_fload (char *FileName)
{
  /*
   **
   ** Load a BASIC program from the specified 'FileName'.
   ** If 'FileName' is NULL, then load from My->ProgramFilename,
   **
   */
  char *Magic_Word;                /* SYNTAX: %INCLUDE literal.file.name */
  int Magic_Length;
  FILE *file;
  char *tbuf;
  int tlen;

  Magic_Word = "%INCLUDE ";        /* SYNTAX: %INCLUDE literal.file.name */
  Magic_Length = bwb_strlen (Magic_Word);
  tbuf = My->MaxLenBuffer;
  tlen = MAXLEN;

  /*
     Just in case you are wondering...
     Although this handles the most common cases, it does not
     handle all possible cases.
     The correct solution is to provide the actual filename (with extension),
     as it exists in the operating system.
   */

  file = nice_open (FileName);
  if (file == NULL)
  {
    WARN_BAD_FILE_NAME;
    return FALSE;
  }
  My->NextValidLineNumber = MINLIN;
  while (fgets (tbuf, tlen, file))        /* bwb_fload */
  {
    tbuf[tlen] = NulChar;
    CleanLine (tbuf);
    if (is_empty_string (tbuf))
    {
      /* ignore */
    }
    else if (bwb_strnicmp (tbuf, "#!", 2) == 0)
    {
      /* Shebang - executable script Linux */
      /* Ignore Line - ejj added 18apr23*/
    }
    else if (bwb_strnicmp (tbuf, Magic_Word, Magic_Length) == 0)
    {
      /* %iNCLUDE */
      int Result;
      int p;
      char varname[NameLengthMax + 1];

      p = Magic_Length;
      if (buff_read_varname (tbuf, &p, varname) == FALSE)
      {
        fprintf (My->SYSOUT->cfp, "%s Filename\n", Magic_Word);
        ResetConsoleColumn ();
        return FALSE;
      }
      My->IncludeLevel++;        /* %INCLUDE */
      Result = bwb_fload (varname);
      My->IncludeLevel--;        /* %INCLUDE */
      if (Result == FALSE)
      {
        fprintf (My->SYSOUT->cfp, "%s %s Failed\n", Magic_Word, varname);
        ResetConsoleColumn ();
        return FALSE;
      }
    }
    else
    {
      /* normal */
      bwb_ladd (tbuf, My->StartMarker, FALSE);
    }
  }

  /* close file stream */

  bwb_fclose (file);                /* file != NULL */

  My->NextValidLineNumber = MINLIN;

  return TRUE;
}

**Comment by kenmartin-unix** [comment]
See bwbasic-3.20ds for update for SheBang.
